name: 'Build'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn run all
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Transpiling